///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Task1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Task1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("c055ec33-47c1-42c2-b640-e60253987970")]
    public partial class Task1Repository : RepoGenBaseFolder
    {
        static Task1Repository instance = new Task1Repository();
        Task1RepositoryFolders.SwagLabsAppFolder _swaglabs;
        Task1RepositoryFolders.SwagLabsMozillaFirefoxAppFolder _swaglabsmozillafirefox;

        /// <summary>
        /// Gets the singleton class instance representing the Task1Repository element repository.
        /// </summary>
        [RepositoryFolder("c055ec33-47c1-42c2-b640-e60253987970")]
        public static Task1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Task1Repository() 
            : base("Task1Repository", "/", null, 0, false, "c055ec33-47c1-42c2-b640-e60253987970", ".\\RepositoryImages\\Task1Repositoryc055ec33.rximgres")
        {
            _swaglabs = new Task1RepositoryFolders.SwagLabsAppFolder(this);
            _swaglabsmozillafirefox = new Task1RepositoryFolders.SwagLabsMozillaFirefoxAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c055ec33-47c1-42c2-b640-e60253987970")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The SwagLabs folder.
        /// </summary>
        [RepositoryFolder("e28d8f9a-0aeb-4cc8-bb36-cfea333456fa")]
        public virtual Task1RepositoryFolders.SwagLabsAppFolder SwagLabs
        {
            get { return _swaglabs; }
        }

        /// <summary>
        /// The SwagLabsMozillaFirefox folder.
        /// </summary>
        [RepositoryFolder("5a294b37-a2e5-429f-a2eb-43c11c4289d3")]
        public virtual Task1RepositoryFolders.SwagLabsMozillaFirefoxAppFolder SwagLabsMozillaFirefox
        {
            get { return _swaglabsmozillafirefox; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Task1RepositoryFolders
    {
        /// <summary>
        /// The SwagLabsAppFolder folder.
        /// </summary>
        [RepositoryFolder("e28d8f9a-0aeb-4cc8-bb36-cfea333456fa")]
        public partial class SwagLabsAppFolder : RepoGenBaseFolder
        {
            Task1RepositoryFolders.CartItemFolder _cartitem;
            Task1RepositoryFolders.CheckoutSummaryContainerFolder _checkoutsummarycontainer;
            Task1RepositoryFolders.CheckoutCompleteContainerFolder _checkoutcompletecontainer;
            RepoItemInfo _usernameInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _loginbuttonInfo;
            RepoItemInfo _productsInfo;
            RepoItemInfo _addtocartsaucelabsbackpackInfo;
            RepoItemInfo _shoppingcartlinkInfo;
            RepoItemInfo _checkoutInfo;
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _postalcodeInfo;
            RepoItemInfo _continueInfo;
            RepoItemInfo _checkoutoverviewInfo;
            RepoItemInfo _yourcartInfo;
            RepoItemInfo _checkoutyourinformationInfo;
            RepoItemInfo _finishInfo;
            RepoItemInfo _checkoutcompleteInfo;
            RepoItemInfo _backtoproductsInfo;
            RepoItemInfo _cart_badgeInfo;

            /// <summary>
            /// Creates a new SwagLabs  folder.
            /// </summary>
            public SwagLabsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SwagLabs", "/dom[@domain='www.saucedemo.com']", parentFolder, 30000, null, false, "e28d8f9a-0aeb-4cc8-bb36-cfea333456fa", "")
            {
                _cartitem = new Task1RepositoryFolders.CartItemFolder(this);
                _checkoutsummarycontainer = new Task1RepositoryFolders.CheckoutSummaryContainerFolder(this);
                _checkoutcompletecontainer = new Task1RepositoryFolders.CheckoutCompleteContainerFolder(this);
                _usernameInfo = new RepoItemInfo(this, "UserName", ".//input[#'user-name']", 30000, null, "79988c3c-d4a6-48f4-9935-5157f255a5af");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//input[#'password']", 30000, null, "68a3988e-0d19-4724-b55d-8effee80ef7c");
                _loginbuttonInfo = new RepoItemInfo(this, "LoginButton", ".//input[#'login-button']", 30000, null, "b195eea9-2bd8-46c3-8c29-7dc495872553");
                _productsInfo = new RepoItemInfo(this, "Products", ".//div[#'header_container']/?/?/span[@innertext='Products']", 30000, null, "a3c61a9b-a624-4344-a31c-fe2bec05877c");
                _addtocartsaucelabsbackpackInfo = new RepoItemInfo(this, "AddToCartSauceLabsBackpack", ".//button[#'add-to-cart-sauce-labs-backpack']", 30000, null, "6ce3f3ce-a2d7-4585-bee5-f12b7bd62935");
                _shoppingcartlinkInfo = new RepoItemInfo(this, "ShoppingCartLink", ".//div[#'shopping_cart_container']", 30000, null, "f159de39-23f3-4e47-8c48-5a0ae8e184a9");
                _checkoutInfo = new RepoItemInfo(this, "Checkout", ".//button[#'checkout']", 30000, null, "c01bf848-38ad-4f4d-95dc-9b164a05ab08");
                _firstnameInfo = new RepoItemInfo(this, "FirstName", ".//input[#'first-name']", 30000, null, "f8910369-8c59-4077-aec1-11a9e91f1944");
                _lastnameInfo = new RepoItemInfo(this, "LastName", ".//input[#'last-name']", 30000, null, "83ae997a-c792-4cf4-9165-89ae6992fedb");
                _postalcodeInfo = new RepoItemInfo(this, "PostalCode", ".//input[#'postal-code']", 30000, null, "04228873-e121-4122-95b6-97ead8c3c752");
                _continueInfo = new RepoItemInfo(this, "Continue", ".//input[#'continue']", 30000, null, "0e9f3e27-3c84-4973-8979-5034941f2f9d");
                _checkoutoverviewInfo = new RepoItemInfo(this, "CheckoutOverview", ".//div[#'header_container']/?/?/span[@innertext='Checkout: Overview']", 30000, null, "55eb3ae3-565a-44ff-9632-739997e675bf");
                _yourcartInfo = new RepoItemInfo(this, "YourCart", ".//div[#'header_container']/?/?/span[@innertext='Your Cart']", 30000, null, "26d73cb2-7fef-4d12-a473-abf8d885a1f9");
                _checkoutyourinformationInfo = new RepoItemInfo(this, "CheckoutYourInformation", ".//div[#'header_container']/?/?/span[@innertext>'Checkout: Your Informatio']", 30000, null, "532d9a86-3a56-419c-9f9d-767b97c06f46");
                _finishInfo = new RepoItemInfo(this, "Finish", ".//button[#'finish']", 30000, null, "e38b82bd-77f3-4352-b13d-a714360138dc");
                _checkoutcompleteInfo = new RepoItemInfo(this, "CheckoutComplete", ".//div[#'header_container']/?/?/span[@innertext='Checkout: Complete!']", 30000, null, "1f004bb4-5480-490b-8ef7-baec4b16d478");
                _backtoproductsInfo = new RepoItemInfo(this, "BackToProducts", ".//button[#'back-to-products']", 30000, null, "953048b2-fe90-4c4f-86ce-85ce0b987b2e");
                _cart_badgeInfo = new RepoItemInfo(this, "cart_badge", ".//div[#'shopping_cart_container']/?/?/span[@safeclass='shopping_cart_badge']", 30000, null, "44bf9571-1531-4a82-9073-6617ae877be7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e28d8f9a-0aeb-4cc8-bb36-cfea333456fa")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e28d8f9a-0aeb-4cc8-bb36-cfea333456fa")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UserName item.
            /// </summary>
            [RepositoryItem("79988c3c-d4a6-48f4-9935-5157f255a5af")]
            public virtual Ranorex.InputTag UserName
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserName item info.
            /// </summary>
            [RepositoryItemInfo("79988c3c-d4a6-48f4-9935-5157f255a5af")]
            public virtual RepoItemInfo UserNameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("68a3988e-0d19-4724-b55d-8effee80ef7c")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("68a3988e-0d19-4724-b55d-8effee80ef7c")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The LoginButton item.
            /// </summary>
            [RepositoryItem("b195eea9-2bd8-46c3-8c29-7dc495872553")]
            public virtual Ranorex.InputTag LoginButton
            {
                get
                {
                    return _loginbuttonInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LoginButton item info.
            /// </summary>
            [RepositoryItemInfo("b195eea9-2bd8-46c3-8c29-7dc495872553")]
            public virtual RepoItemInfo LoginButtonInfo
            {
                get
                {
                    return _loginbuttonInfo;
                }
            }

            /// <summary>
            /// The Products item.
            /// </summary>
            [RepositoryItem("a3c61a9b-a624-4344-a31c-fe2bec05877c")]
            public virtual Ranorex.SpanTag Products
            {
                get
                {
                    return _productsInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Products item info.
            /// </summary>
            [RepositoryItemInfo("a3c61a9b-a624-4344-a31c-fe2bec05877c")]
            public virtual RepoItemInfo ProductsInfo
            {
                get
                {
                    return _productsInfo;
                }
            }

            /// <summary>
            /// The AddToCartSauceLabsBackpack item.
            /// </summary>
            [RepositoryItem("6ce3f3ce-a2d7-4585-bee5-f12b7bd62935")]
            public virtual Ranorex.ButtonTag AddToCartSauceLabsBackpack
            {
                get
                {
                    return _addtocartsaucelabsbackpackInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The AddToCartSauceLabsBackpack item info.
            /// </summary>
            [RepositoryItemInfo("6ce3f3ce-a2d7-4585-bee5-f12b7bd62935")]
            public virtual RepoItemInfo AddToCartSauceLabsBackpackInfo
            {
                get
                {
                    return _addtocartsaucelabsbackpackInfo;
                }
            }

            /// <summary>
            /// The ShoppingCartLink item.
            /// </summary>
            [RepositoryItem("f159de39-23f3-4e47-8c48-5a0ae8e184a9")]
            public virtual Ranorex.DivTag ShoppingCartLink
            {
                get
                {
                    return _shoppingcartlinkInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ShoppingCartLink item info.
            /// </summary>
            [RepositoryItemInfo("f159de39-23f3-4e47-8c48-5a0ae8e184a9")]
            public virtual RepoItemInfo ShoppingCartLinkInfo
            {
                get
                {
                    return _shoppingcartlinkInfo;
                }
            }

            /// <summary>
            /// The Checkout item.
            /// </summary>
            [RepositoryItem("c01bf848-38ad-4f4d-95dc-9b164a05ab08")]
            public virtual Ranorex.ButtonTag Checkout
            {
                get
                {
                    return _checkoutInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Checkout item info.
            /// </summary>
            [RepositoryItemInfo("c01bf848-38ad-4f4d-95dc-9b164a05ab08")]
            public virtual RepoItemInfo CheckoutInfo
            {
                get
                {
                    return _checkoutInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("f8910369-8c59-4077-aec1-11a9e91f1944")]
            public virtual Ranorex.InputTag FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("f8910369-8c59-4077-aec1-11a9e91f1944")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("83ae997a-c792-4cf4-9165-89ae6992fedb")]
            public virtual Ranorex.InputTag LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("83ae997a-c792-4cf4-9165-89ae6992fedb")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The PostalCode item.
            /// </summary>
            [RepositoryItem("04228873-e121-4122-95b6-97ead8c3c752")]
            public virtual Ranorex.InputTag PostalCode
            {
                get
                {
                    return _postalcodeInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PostalCode item info.
            /// </summary>
            [RepositoryItemInfo("04228873-e121-4122-95b6-97ead8c3c752")]
            public virtual RepoItemInfo PostalCodeInfo
            {
                get
                {
                    return _postalcodeInfo;
                }
            }

            /// <summary>
            /// The Continue item.
            /// </summary>
            [RepositoryItem("0e9f3e27-3c84-4973-8979-5034941f2f9d")]
            public virtual Ranorex.InputTag Continue
            {
                get
                {
                    return _continueInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Continue item info.
            /// </summary>
            [RepositoryItemInfo("0e9f3e27-3c84-4973-8979-5034941f2f9d")]
            public virtual RepoItemInfo ContinueInfo
            {
                get
                {
                    return _continueInfo;
                }
            }

            /// <summary>
            /// The CheckoutOverview item.
            /// </summary>
            [RepositoryItem("55eb3ae3-565a-44ff-9632-739997e675bf")]
            public virtual Ranorex.SpanTag CheckoutOverview
            {
                get
                {
                    return _checkoutoverviewInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The CheckoutOverview item info.
            /// </summary>
            [RepositoryItemInfo("55eb3ae3-565a-44ff-9632-739997e675bf")]
            public virtual RepoItemInfo CheckoutOverviewInfo
            {
                get
                {
                    return _checkoutoverviewInfo;
                }
            }

            /// <summary>
            /// The YourCart item.
            /// </summary>
            [RepositoryItem("26d73cb2-7fef-4d12-a473-abf8d885a1f9")]
            public virtual Ranorex.SpanTag YourCart
            {
                get
                {
                    return _yourcartInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The YourCart item info.
            /// </summary>
            [RepositoryItemInfo("26d73cb2-7fef-4d12-a473-abf8d885a1f9")]
            public virtual RepoItemInfo YourCartInfo
            {
                get
                {
                    return _yourcartInfo;
                }
            }

            /// <summary>
            /// The CheckoutYourInformation item.
            /// </summary>
            [RepositoryItem("532d9a86-3a56-419c-9f9d-767b97c06f46")]
            public virtual Ranorex.SpanTag CheckoutYourInformation
            {
                get
                {
                    return _checkoutyourinformationInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The CheckoutYourInformation item info.
            /// </summary>
            [RepositoryItemInfo("532d9a86-3a56-419c-9f9d-767b97c06f46")]
            public virtual RepoItemInfo CheckoutYourInformationInfo
            {
                get
                {
                    return _checkoutyourinformationInfo;
                }
            }

            /// <summary>
            /// The Finish item.
            /// </summary>
            [RepositoryItem("e38b82bd-77f3-4352-b13d-a714360138dc")]
            public virtual Ranorex.ButtonTag Finish
            {
                get
                {
                    return _finishInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Finish item info.
            /// </summary>
            [RepositoryItemInfo("e38b82bd-77f3-4352-b13d-a714360138dc")]
            public virtual RepoItemInfo FinishInfo
            {
                get
                {
                    return _finishInfo;
                }
            }

            /// <summary>
            /// The CheckoutComplete item.
            /// </summary>
            [RepositoryItem("1f004bb4-5480-490b-8ef7-baec4b16d478")]
            public virtual Ranorex.SpanTag CheckoutComplete
            {
                get
                {
                    return _checkoutcompleteInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The CheckoutComplete item info.
            /// </summary>
            [RepositoryItemInfo("1f004bb4-5480-490b-8ef7-baec4b16d478")]
            public virtual RepoItemInfo CheckoutCompleteInfo
            {
                get
                {
                    return _checkoutcompleteInfo;
                }
            }

            /// <summary>
            /// The BackToProducts item.
            /// </summary>
            [RepositoryItem("953048b2-fe90-4c4f-86ce-85ce0b987b2e")]
            public virtual Ranorex.ButtonTag BackToProducts
            {
                get
                {
                    return _backtoproductsInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The BackToProducts item info.
            /// </summary>
            [RepositoryItemInfo("953048b2-fe90-4c4f-86ce-85ce0b987b2e")]
            public virtual RepoItemInfo BackToProductsInfo
            {
                get
                {
                    return _backtoproductsInfo;
                }
            }

            /// <summary>
            /// The cart_badge item.
            /// </summary>
            [RepositoryItem("44bf9571-1531-4a82-9073-6617ae877be7")]
            public virtual Ranorex.SpanTag cart_badge
            {
                get
                {
                    return _cart_badgeInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The cart_badge item info.
            /// </summary>
            [RepositoryItemInfo("44bf9571-1531-4a82-9073-6617ae877be7")]
            public virtual RepoItemInfo cart_badgeInfo
            {
                get
                {
                    return _cart_badgeInfo;
                }
            }

            /// <summary>
            /// The CartItem folder.
            /// </summary>
            [RepositoryFolder("32af22a2-a649-4343-931f-4ae75a969815")]
            public virtual Task1RepositoryFolders.CartItemFolder CartItem
            {
                get { return _cartitem; }
            }

            /// <summary>
            /// The CheckoutSummaryContainer folder.
            /// </summary>
            [RepositoryFolder("7ac2a9b9-1acb-4d31-8656-3890a0b5dc3b")]
            public virtual Task1RepositoryFolders.CheckoutSummaryContainerFolder CheckoutSummaryContainer
            {
                get { return _checkoutsummarycontainer; }
            }

            /// <summary>
            /// The CheckoutCompleteContainer folder.
            /// </summary>
            [RepositoryFolder("be8ec2ec-3849-4218-8e7e-b8c10520d8ad")]
            public virtual Task1RepositoryFolders.CheckoutCompleteContainerFolder CheckoutCompleteContainer
            {
                get { return _checkoutcompletecontainer; }
            }
        }

        /// <summary>
        /// The CartItemFolder folder.
        /// </summary>
        [RepositoryFolder("32af22a2-a649-4343-931f-4ae75a969815")]
        public partial class CartItemFolder : RepoGenBaseFolder
        {
            RepoItemInfo _item_nameInfo;
            RepoItemInfo _item_priceInfo;
            RepoItemInfo _cart_quantityInfo;
            RepoItemInfo _item_descriptionInfo;

            /// <summary>
            /// Creates a new CartItem  folder.
            /// </summary>
            public CartItemFolder(RepoGenBaseFolder parentFolder) :
                    base("CartItem", ".//div[#'cart_contents_container']/?/div[@safeclass='cart_list']/div[@safeclass='cart_item']", parentFolder, 30000, null, false, "32af22a2-a649-4343-931f-4ae75a969815", "")
            {
                _item_nameInfo = new RepoItemInfo(this, "Item_name", "?/?/div[@safeclass='inventory_item_name']", 30000, null, "9a3435d2-103b-4712-b507-c6eaa2f864ad");
                _item_priceInfo = new RepoItemInfo(this, "item_price", "?/?/div[@safeclass='inventory_item_price']", 30000, null, "8362ced5-0271-49c4-8c17-c10277a0e63d");
                _cart_quantityInfo = new RepoItemInfo(this, "Cart_quantity", "div[@safeclass='cart_quantity']", 30000, null, "b72fedf4-ad07-4d8a-9b42-d9cfd839a013");
                _item_descriptionInfo = new RepoItemInfo(this, "item_description", "?/?/div[@safeclass='inventory_item_desc']", 30000, null, "8da3fc77-1ff2-4a6b-b8a0-b5bc19eb5c35");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("32af22a2-a649-4343-931f-4ae75a969815")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("32af22a2-a649-4343-931f-4ae75a969815")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Item_name item.
            /// </summary>
            [RepositoryItem("9a3435d2-103b-4712-b507-c6eaa2f864ad")]
            public virtual Ranorex.DivTag Item_name
            {
                get
                {
                    return _item_nameInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Item_name item info.
            /// </summary>
            [RepositoryItemInfo("9a3435d2-103b-4712-b507-c6eaa2f864ad")]
            public virtual RepoItemInfo Item_nameInfo
            {
                get
                {
                    return _item_nameInfo;
                }
            }

            /// <summary>
            /// The item_price item.
            /// </summary>
            [RepositoryItem("8362ced5-0271-49c4-8c17-c10277a0e63d")]
            public virtual Ranorex.DivTag item_price
            {
                get
                {
                    return _item_priceInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The item_price item info.
            /// </summary>
            [RepositoryItemInfo("8362ced5-0271-49c4-8c17-c10277a0e63d")]
            public virtual RepoItemInfo item_priceInfo
            {
                get
                {
                    return _item_priceInfo;
                }
            }

            /// <summary>
            /// The Cart_quantity item.
            /// </summary>
            [RepositoryItem("b72fedf4-ad07-4d8a-9b42-d9cfd839a013")]
            public virtual Ranorex.DivTag Cart_quantity
            {
                get
                {
                    return _cart_quantityInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Cart_quantity item info.
            /// </summary>
            [RepositoryItemInfo("b72fedf4-ad07-4d8a-9b42-d9cfd839a013")]
            public virtual RepoItemInfo Cart_quantityInfo
            {
                get
                {
                    return _cart_quantityInfo;
                }
            }

            /// <summary>
            /// The item_description item.
            /// </summary>
            [RepositoryItem("8da3fc77-1ff2-4a6b-b8a0-b5bc19eb5c35")]
            public virtual Ranorex.DivTag item_description
            {
                get
                {
                    return _item_descriptionInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The item_description item info.
            /// </summary>
            [RepositoryItemInfo("8da3fc77-1ff2-4a6b-b8a0-b5bc19eb5c35")]
            public virtual RepoItemInfo item_descriptionInfo
            {
                get
                {
                    return _item_descriptionInfo;
                }
            }
        }

        /// <summary>
        /// The CheckoutSummaryContainerFolder folder.
        /// </summary>
        [RepositoryFolder("7ac2a9b9-1acb-4d31-8656-3890a0b5dc3b")]
        public partial class CheckoutSummaryContainerFolder : RepoGenBaseFolder
        {
            Task1RepositoryFolders.CartListFolder _cartlist;
            RepoItemInfo _summary_taxInfo;
            RepoItemInfo _summary_totalInfo;
            RepoItemInfo _summary_subtotalInfo;

            /// <summary>
            /// Creates a new CheckoutSummaryContainer  folder.
            /// </summary>
            public CheckoutSummaryContainerFolder(RepoGenBaseFolder parentFolder) :
                    base("CheckoutSummaryContainer", ".//div[#'checkout_summary_container']", parentFolder, 30000, null, false, "7ac2a9b9-1acb-4d31-8656-3890a0b5dc3b", "")
            {
                _cartlist = new Task1RepositoryFolders.CartListFolder(this);
                _summary_taxInfo = new RepoItemInfo(this, "summary_tax", ".//div[@safeclass='summary_tax_label']", 30000, null, "baa3f0bf-7578-4071-a190-723ce3ca5a5d");
                _summary_totalInfo = new RepoItemInfo(this, "summary_total", ".//div[@safeclass='summary_total_label']", 30000, null, "ab43e7bb-1941-4ac1-88e8-a35238932739");
                _summary_subtotalInfo = new RepoItemInfo(this, "summary_subtotal", ".//div[@safeclass='summary_subtotal_label']", 30000, null, "533cee77-e34d-41b8-9482-63c62e87e001");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7ac2a9b9-1acb-4d31-8656-3890a0b5dc3b")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7ac2a9b9-1acb-4d31-8656-3890a0b5dc3b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The summary_tax item.
            /// </summary>
            [RepositoryItem("baa3f0bf-7578-4071-a190-723ce3ca5a5d")]
            public virtual Ranorex.DivTag summary_tax
            {
                get
                {
                    return _summary_taxInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The summary_tax item info.
            /// </summary>
            [RepositoryItemInfo("baa3f0bf-7578-4071-a190-723ce3ca5a5d")]
            public virtual RepoItemInfo summary_taxInfo
            {
                get
                {
                    return _summary_taxInfo;
                }
            }

            /// <summary>
            /// The summary_total item.
            /// </summary>
            [RepositoryItem("ab43e7bb-1941-4ac1-88e8-a35238932739")]
            public virtual Ranorex.DivTag summary_total
            {
                get
                {
                    return _summary_totalInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The summary_total item info.
            /// </summary>
            [RepositoryItemInfo("ab43e7bb-1941-4ac1-88e8-a35238932739")]
            public virtual RepoItemInfo summary_totalInfo
            {
                get
                {
                    return _summary_totalInfo;
                }
            }

            /// <summary>
            /// The summary_subtotal item.
            /// </summary>
            [RepositoryItem("533cee77-e34d-41b8-9482-63c62e87e001")]
            public virtual Ranorex.DivTag summary_subtotal
            {
                get
                {
                    return _summary_subtotalInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The summary_subtotal item info.
            /// </summary>
            [RepositoryItemInfo("533cee77-e34d-41b8-9482-63c62e87e001")]
            public virtual RepoItemInfo summary_subtotalInfo
            {
                get
                {
                    return _summary_subtotalInfo;
                }
            }

            /// <summary>
            /// The CartList folder.
            /// </summary>
            [RepositoryFolder("dc7bca83-3850-4bf8-8e94-546c79bc0f57")]
            public virtual Task1RepositoryFolders.CartListFolder CartList
            {
                get { return _cartlist; }
            }
        }

        /// <summary>
        /// The CartListFolder folder.
        /// </summary>
        [RepositoryFolder("dc7bca83-3850-4bf8-8e94-546c79bc0f57")]
        public partial class CartListFolder : RepoGenBaseFolder
        {
            Task1RepositoryFolders.CartItemFolder1 _cartitem;

            /// <summary>
            /// Creates a new CartList  folder.
            /// </summary>
            public CartListFolder(RepoGenBaseFolder parentFolder) :
                    base("CartList", "?/div[@safeclass='cart_list']", parentFolder, 30000, null, false, "dc7bca83-3850-4bf8-8e94-546c79bc0f57", "")
            {
                _cartitem = new Task1RepositoryFolders.CartItemFolder1(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("dc7bca83-3850-4bf8-8e94-546c79bc0f57")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("dc7bca83-3850-4bf8-8e94-546c79bc0f57")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CartItem folder.
            /// </summary>
            [RepositoryFolder("170afe0f-00ea-467c-b366-9247eabc5dd3")]
            public virtual Task1RepositoryFolders.CartItemFolder1 CartItem
            {
                get { return _cartitem; }
            }
        }

        /// <summary>
        /// The CartItemFolder1 folder.
        /// </summary>
        [RepositoryFolder("170afe0f-00ea-467c-b366-9247eabc5dd3")]
        public partial class CartItemFolder1 : RepoGenBaseFolder
        {
            RepoItemInfo _item_nameInfo;
            RepoItemInfo _cart_quantityInfo;
            RepoItemInfo _item__priceInfo;
            RepoItemInfo _item_descriptionInfo;

            /// <summary>
            /// Creates a new CartItem  folder.
            /// </summary>
            public CartItemFolder1(RepoGenBaseFolder parentFolder) :
                    base("CartItem", "div[@safeclass='cart_item']", parentFolder, 30000, null, false, "170afe0f-00ea-467c-b366-9247eabc5dd3", "")
            {
                _item_nameInfo = new RepoItemInfo(this, "item_name", "?/?/?/div[@safeclass='inventory_item_name']", 30000, null, "812e9ef1-e721-452e-8c3d-63763c015c8a");
                _cart_quantityInfo = new RepoItemInfo(this, "cart_quantity", "div[@safeclass='cart_quantity']", 30000, null, "6727bc2c-3a4d-4a85-9e48-bd47e721cb1b");
                _item__priceInfo = new RepoItemInfo(this, "item__price", "?/?/div[@safeclass='inventory_item_price']", 30000, null, "e9145930-81c1-4cd8-ba30-da5bcaf36da8");
                _item_descriptionInfo = new RepoItemInfo(this, "item_description", "?/?/div[@safeclass='inventory_item_desc']", 30000, null, "6aaa94cb-0456-4c00-a959-c7cb8cedaa27");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("170afe0f-00ea-467c-b366-9247eabc5dd3")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("170afe0f-00ea-467c-b366-9247eabc5dd3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The item_name item.
            /// </summary>
            [RepositoryItem("812e9ef1-e721-452e-8c3d-63763c015c8a")]
            public virtual Ranorex.DivTag item_name
            {
                get
                {
                    return _item_nameInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The item_name item info.
            /// </summary>
            [RepositoryItemInfo("812e9ef1-e721-452e-8c3d-63763c015c8a")]
            public virtual RepoItemInfo item_nameInfo
            {
                get
                {
                    return _item_nameInfo;
                }
            }

            /// <summary>
            /// The cart_quantity item.
            /// </summary>
            [RepositoryItem("6727bc2c-3a4d-4a85-9e48-bd47e721cb1b")]
            public virtual Ranorex.DivTag cart_quantity
            {
                get
                {
                    return _cart_quantityInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The cart_quantity item info.
            /// </summary>
            [RepositoryItemInfo("6727bc2c-3a4d-4a85-9e48-bd47e721cb1b")]
            public virtual RepoItemInfo cart_quantityInfo
            {
                get
                {
                    return _cart_quantityInfo;
                }
            }

            /// <summary>
            /// The item__price item.
            /// </summary>
            [RepositoryItem("e9145930-81c1-4cd8-ba30-da5bcaf36da8")]
            public virtual Ranorex.DivTag item__price
            {
                get
                {
                    return _item__priceInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The item__price item info.
            /// </summary>
            [RepositoryItemInfo("e9145930-81c1-4cd8-ba30-da5bcaf36da8")]
            public virtual RepoItemInfo item__priceInfo
            {
                get
                {
                    return _item__priceInfo;
                }
            }

            /// <summary>
            /// The item_description item.
            /// </summary>
            [RepositoryItem("6aaa94cb-0456-4c00-a959-c7cb8cedaa27")]
            public virtual Ranorex.DivTag item_description
            {
                get
                {
                    return _item_descriptionInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The item_description item info.
            /// </summary>
            [RepositoryItemInfo("6aaa94cb-0456-4c00-a959-c7cb8cedaa27")]
            public virtual RepoItemInfo item_descriptionInfo
            {
                get
                {
                    return _item_descriptionInfo;
                }
            }
        }

        /// <summary>
        /// The CheckoutCompleteContainerFolder folder.
        /// </summary>
        [RepositoryFolder("be8ec2ec-3849-4218-8e7e-b8c10520d8ad")]
        public partial class CheckoutCompleteContainerFolder : RepoGenBaseFolder
        {
            RepoItemInfo _complete_textInfo;
            RepoItemInfo _complete_headerInfo;
            RepoItemInfo _ponyexpressInfo;

            /// <summary>
            /// Creates a new CheckoutCompleteContainer  folder.
            /// </summary>
            public CheckoutCompleteContainerFolder(RepoGenBaseFolder parentFolder) :
                    base("CheckoutCompleteContainer", ".//div[#'checkout_complete_container']", parentFolder, 30000, null, false, "be8ec2ec-3849-4218-8e7e-b8c10520d8ad", "")
            {
                _complete_textInfo = new RepoItemInfo(this, "Complete_text", "div[@safeclass='complete-text']", 30000, null, "8e07c24e-7b6d-48b4-aa2e-091ed80111af");
                _complete_headerInfo = new RepoItemInfo(this, "complete_header", "h2[@safeclass='complete-header']", 30000, null, "257a47da-7290-44c9-951c-1d294e49f1af");
                _ponyexpressInfo = new RepoItemInfo(this, "PonyExpress", "img[@safeclass='pony_express']", 30000, null, "298c404f-eeff-431c-8f45-ae279e03aa87");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("be8ec2ec-3849-4218-8e7e-b8c10520d8ad")]
            public virtual Ranorex.DivTag Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("be8ec2ec-3849-4218-8e7e-b8c10520d8ad")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Complete_text item.
            /// </summary>
            [RepositoryItem("8e07c24e-7b6d-48b4-aa2e-091ed80111af")]
            public virtual Ranorex.DivTag Complete_text
            {
                get
                {
                    return _complete_textInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Complete_text item info.
            /// </summary>
            [RepositoryItemInfo("8e07c24e-7b6d-48b4-aa2e-091ed80111af")]
            public virtual RepoItemInfo Complete_textInfo
            {
                get
                {
                    return _complete_textInfo;
                }
            }

            /// <summary>
            /// The complete_header item.
            /// </summary>
            [RepositoryItem("257a47da-7290-44c9-951c-1d294e49f1af")]
            public virtual Ranorex.H2Tag complete_header
            {
                get
                {
                    return _complete_headerInfo.CreateAdapter<Ranorex.H2Tag>(true);
                }
            }

            /// <summary>
            /// The complete_header item info.
            /// </summary>
            [RepositoryItemInfo("257a47da-7290-44c9-951c-1d294e49f1af")]
            public virtual RepoItemInfo complete_headerInfo
            {
                get
                {
                    return _complete_headerInfo;
                }
            }

            /// <summary>
            /// The PonyExpress item.
            /// </summary>
            [RepositoryItem("298c404f-eeff-431c-8f45-ae279e03aa87")]
            public virtual Ranorex.ImgTag PonyExpress
            {
                get
                {
                    return _ponyexpressInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The PonyExpress item info.
            /// </summary>
            [RepositoryItemInfo("298c404f-eeff-431c-8f45-ae279e03aa87")]
            public virtual RepoItemInfo PonyExpressInfo
            {
                get
                {
                    return _ponyexpressInfo;
                }
            }
        }

        /// <summary>
        /// The SwagLabsMozillaFirefoxAppFolder folder.
        /// </summary>
        [RepositoryFolder("5a294b37-a2e5-429f-a2eb-43c11c4289d3")]
        public partial class SwagLabsMozillaFirefoxAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _swaglabsInfo;

            /// <summary>
            /// Creates a new SwagLabsMozillaFirefox  folder.
            /// </summary>
            public SwagLabsMozillaFirefoxAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SwagLabsMozillaFirefox", "/form[@title>'Swag Labs — Mozilla Firef']", parentFolder, 30000, null, true, "5a294b37-a2e5-429f-a2eb-43c11c4289d3", "")
            {
                _swaglabsInfo = new RepoItemInfo(this, "SwagLabs", "toolbar[@accessiblename='Browser tabs']/?/?/tabpage[@accessiblename='Swag Labs']", 30000, null, "ec3f51cc-7b13-4d89-864e-8dfc809e26df");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5a294b37-a2e5-429f-a2eb-43c11c4289d3")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5a294b37-a2e5-429f-a2eb-43c11c4289d3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SwagLabs item.
            /// </summary>
            [RepositoryItem("ec3f51cc-7b13-4d89-864e-8dfc809e26df")]
            public virtual Ranorex.TabPage SwagLabs
            {
                get
                {
                    return _swaglabsInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The SwagLabs item info.
            /// </summary>
            [RepositoryItemInfo("ec3f51cc-7b13-4d89-864e-8dfc809e26df")]
            public virtual RepoItemInfo SwagLabsInfo
            {
                get
                {
                    return _swaglabsInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
